services:
  iris_community:
    image: 'intersystemsdc/iris-community:latest'
    hostname: iris-community
    ports:
      - ${IRIS_SUPERSERVER_PORT:-51972}:1972
      - ${IRIS_WEB_PORT:-52775}:52773
    environment:
      - IRIS_USERNAME=${IRIS_USERNAME:-SuperUser}
      - IRIS_PASSWORD=${IRIS_PASSWORD:?Set IRIS_PASSWORD in .env}
    volumes:
      - ./durable/:/durable/
    networks:
      - iris-community-network

networks:
  iris-community-network:
    external: false
